// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_max_from_sel_fast
int find_max_from_sel_fast(NumericVector x, IntegerVector which);
RcppExport SEXP _DiffEmbSeq_find_max_from_sel_fast(SEXP xSEXP, SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(find_max_from_sel_fast(x, which));
    return rcpp_result_gen;
END_RCPP
}
// find_min_from_sel_fast
int find_min_from_sel_fast(NumericVector x, IntegerVector which);
RcppExport SEXP _DiffEmbSeq_find_min_from_sel_fast(SEXP xSEXP, SEXP whichSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type which(whichSEXP);
    rcpp_result_gen = Rcpp::wrap(find_min_from_sel_fast(x, which));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DiffEmbSeq_find_max_from_sel_fast", (DL_FUNC) &_DiffEmbSeq_find_max_from_sel_fast, 2},
    {"_DiffEmbSeq_find_min_from_sel_fast", (DL_FUNC) &_DiffEmbSeq_find_min_from_sel_fast, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DiffEmbSeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
