# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumz <- function(x) {
    .Call(`_DiffEmbSeq_cumz`, x)
}

cumz_which_abs_max <- function(x) {
    .Call(`_DiffEmbSeq_cumz_which_abs_max`, x)
}

