# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumz_which_abs_max <- function(x) {
    .Call(`_lemur_cumz_which_abs_max`, x)
}

cum_brls_which_abs_max <- function(y, X, group, contrast, penalty) {
    .Call(`_lemur_cum_brls_which_abs_max`, y, X, group, contrast, penalty)
}

