# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cumz_which_abs_max <- function(x, min_neighborhood_size) {
    .Call(`_lemur_cumz_which_abs_max`, x, min_neighborhood_size)
}

cum_brls_which_abs_max <- function(y, X, group, contrast, penalty, min_neighborhood_size) {
    .Call(`_lemur_cum_brls_which_abs_max`, y, X, group, contrast, penalty, min_neighborhood_size)
}

count_neighbors_fast <- function(knn_mat, indices) {
    .Call(`_lemur_count_neighbors_fast`, knn_mat, indices)
}

